* 简介
  AJAX 是一种在无需重新加载整个网页的情况下，能够更新部分网页的技术。通过在后台
  与服务器进行少量数据交换，AJAX 可使网页实现异步更新。这意味着可在不重新加载整
  个网页的情况下，对网页的某部分进行更新。
  传统的网页(不使用 AJAX)如果需要更新内容，必须重载整个网页面。

* 创建 XMLHttpRequest 对象
  XMLHttpRequest 是 AJAX 的基础。
  所有现代浏览器均支持 XMLHttpRequest 对象(IE5 和 IE6 使用 ActiveXObject).
  XMLHttpRequest 用于在后台与服务器交换数据。这意味着可在不重新加载整个网页的情
  况下，对网页的某部分进行更新。
  为了应对所有的现在浏览器，包括 IE5 和 IE6，请检查浏览器是否支持 XMLHttpRequest
  对象。若支持，则创建 XMLHttpRequest 对象，否则创建 ActiveXObject,如下例:

  var xmlhttp;
  if (window.XMLHttpRequest){
  // code for IE7+, Firefox, chrome, Opera, Safari
  xmlhttp = new XMLHttpRequest();
  } else {
  // code for IE6, IE5
  xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
  }
* 向服务器发送请求
  XMLHttpRequest 对象用于和服务器交换数据。
  若需将请求发送到服务器，使用 XMLHttpRequest 对象的 open() 和 send() 方法。

* 服务器响应
  若需获得来自服务器的相应，使用 XMLHttpRequest 对象的 responseText 或
  responseXML 属性。
* onreadystatechange 事件
  当请求被发送到服务器时，我们需要执行一些基于相应的任务。每当 readyState 改变时，
  就会触发 onreadystatechange 事件。 readyState 属性存有 XMLHttpRequest 的状态信
  息。
  XMLHttpRequest 对象的三个重要属性:
  1)onreadystatechange: 存储函数(或函数名),每当 readyState 属性改变时，就会调用
  该函数。
  2)readyState: 存有 XMLHttpRequest 的状态，从 0 到 4 发生变化，0 表示未初始化，
  1 表示服务器连接已建立，2 表示请求已接收，3 表示请求处理中，4 表示请求已完成，
  且响应已就绪。
  3)status: 200 表示 OK, 404 表示未找到页面.
  当 readyState 等于 4 且状态为 200 时，表示响应已就绪.
