* angular.js 应用的应用流程
  + A user requests the first page of your application
  + The user's browser makes an HTTP connection to your server and loads
    the *index.html* page containing your template
  + Angular loads into the page, waits for the page to be fully loaded, and
    then looks for *ng-app* to define its template boundaries
  + Angular traverses the template and looks for directives and bindings. This
    results in registration of listeners and DOM manipulation, as well as
    fetching initial data from the server. The end result of this work is that
    the app is bootstrapped and the template is converted into view as a DOM
  + You connect to your server to load additional data you need to show the
    user as needed.
* 我的理解
  我对 angular.js 的理解是:
  + 限定作用域
  + 数据绑定
* 常用的 directive 和一些概念
** ng-app
   The *ng-app* directive lets you tell Angular which part of your page it
   should expect to manage. If you're building an all-Angular application, you
   should include *ng-app* as part of the <html> tag.
** ng-controller
** ng-repeat

   如
   
   <ul ng-controller="RepeatItems">
     <li ng-repeat="friend in friends">
	   {{$index}} of firend is {{friend.name}}, age is {{friend.age}}
	 </li>
   </ul>

   function RepeatItems($scope) {
     $scope.friends = [
	   {name: 'flyer', age: 24},
	   {name: 'flx', age: 22},
	   {name: 'test', age: 3}
	 ];
   }
** $scope
*** 作用
	连接 controller 和 view 的全局变量.
*** $watch() 方法
	可用它来监视 *angular expression* 的变化,如

	function StartUpController($scope) {
	  $scope.funding = {
	    startingEstimate: 0,
	  };

	  computeNeeded = function() {
	    $scope.funding.needed = $scope.funding.startingEstimate * 10;
	  };

	  $scope.$watch('funding.startingEstimate', computeNeeded);
	}

	注意 $watch() 的第一个参数,是个 string. This string is evaluated as
	something called an *Angular expression*. Expression can do simple
	operations and have access to the properties in the *$scope* object.
x** event-handling directives
   如 ng-change, ng-submit, ng-click, ng-dbclick ...

   使用 angular.js 中的这些 directive 的好处:
   + Behave the same in every browser. Angular takes care of the differences
     for you
   + Do not operate on the global namespace. The expressions you specify can
     only access functions and data that is in the scope of the element's
     controller
** template
   Templates in Angular applications are just HTML documents that we load from
   the server or define in a <script> tag like any other static resource.
   You define your UI in the template, using standard HTML plus Angular
   directives where you need UI components.
** template 和 data 分离的好处
   + By structuring your application with Angular, your application's templates
     are kept separate from the data that populates them. The result of this is
     that these templates are now *cacheable* . Only new data need come down to
     the browser after the first load. Just as with JavaScript, images, CSS,
     and other resources, caching these templates can give your application
     even better performance.
* Best Practices
** 使用 module
   目的是: Keeping things out of the global namespace is a good thing.
   通过以下例子,可以学习 module 的用法:

   <html ng-app="myApp">
     <head>
	   <script src="js/angular.min.js">
	 </head>

	 <body ng-controller="TextController">
	   <p ng-bind="someText.msg"></p>

	   <script>
	     var myAppModule = angular.module('myApp', []);
		 
		 myAppModule.controller('TextController', function($scope) {
		   var someText = {};
		   
		   someText.msg = 'Just a test';
		   
		   $scope.someText = someText;
		 });
	   </script>
	 </body>
   </html>
** ng-bind 和 {{}}
   绑定数据可用如下两种形式:
   
   <p>{{item}}</p>
   或 
   <p ng-bind="item"></p>

   二者是等价的.
   在 web 应用中第一个载入的页面中，最好使用第二中形式，因为若载入慢，用户可能会
   看到 '{{item}}' 这样的语句.原因是: The browser loads the HTML pages, renders
   it, and only then does Angular get a chance to interpret it as you intended.
   而第二种形式则不会.在除此之外的页面中，常用第一种形式.
