* what
  jQuery 是一个 Javascript 库。
* 语法
  jQuery 语法是为 HTML 元素的选取编制的，可对元素执行某些操作。
  基本语法: $(selector).action()
  1)美元符号定义 jQuery
  2)选择符(selector)“查询”和“查找” HTML 元素
  3)jQuery 的 action() 执行对元素的操作。
  在很多的 jQuery 函数中通常都会有如下格式:
  
  $(document).ready(
  -- jQuery functions go here --
  );

  这是为了防止文档在没有加载(就绪)之前运行 jQuery 代码。若在文档没有加载前就运行
  函数，操作可能失败。
* 选择器
  jQuery *元素选择器* 和 *属性选择器* 允许您通过标签名、属性名或内容对 HTML 元素
  进行选择。还有 *CSS 选择器* 可用于改变 HTML 元素的 CSS 属性。
  选择器允许您对 HTML 元素组或单个元素进行操作。

* 事件
  jQuery 是为事件处理特别设计的，jQuery 事件处理方法是 jQuery 中的核心函数。
  *事件处理程序* 指的是当 HTML 中发生某些事件时所调用的方法。
  事件方法会触发匹配元素的事件，或将函数绑定到所有匹配元素的某个事件。
* 命名冲突
  jQuery 使用 $ 符号作为 jQuery 的简介方式，某些其他 JavaScript 库中的函数(如
  Prototype)同样使用 $ 符号。jQuery 使用名为 noConflict() 的方法来解决该问题。
  如以下代码:
  
  var jq = jQuery.noConflict();
  jq(document).ready(function(){
  jq("button").click(function(){
  jq("p").hide();
  });
  });
* 一些原则
  由于 jQuery 是为处理 HTML 事件而特别设计的，则当遵循以下原则时，代码会更恰当且
  更易维护:
  1)把所有 jQuery 代码置于时间处理函数中
  2)把所有事件处理函数置于文档就绪事件处理器中
  3)把 jQuery 代码置于单独的 .js 文件中
  4)若存在名称冲突，则重命名 jQuery 库
* 效果
  jQuery 可以创建隐藏、显示、切换、滑动及自定义动画等效果。
  常见的有:
  hide()、fadeTo()、animate()、toggle()、slideDown()、slideUp()、slideToggle()、
  fadeIn()、fadeOut()、fadeTo()、show()
* callback 函数
  callback 函数在当前动画 100% 完成后执行。
* html 操作
  jQuery 包含很多供改变和操作 HTML 的强大函数。如:
  $(selector).html(content)      改变被选元素的(内部)HTML
  $(selector).append(content)    向被选元素的(内部)HTML追加内容
  $(selector).prepend(content)   向被选元素的(内部)HTML"预置"内容
  $(selector).after(content)     在被选元素之后添加HTML
  $(selector).before(content)    在被选元素之前添加HTML

* css 函数
  jQuery 拥有三种用于 css 操作的重要函数:
  1)$(selector).css(name,value)
  2)$(selector).css({properties})
  3)$(selector).css(name)
* size 操作
