* PDO
** PDO::prepare 和 PDO::execute
   在通过 prepare() 时， '?' 不能加任何引号。在 execute() 时，不能使用 SQL 的默
   认函数，这点儿在添加当前日期时尤其明显。若要添加日期，先通过 date() 函数建立
   一个指定格式的日期，然后加入到 execute() 语句中。
** 使用 PDO 后获得数据库查询的行数
  $sql_num         = "SELECT COUNT(*) FROM $table";
  $proxy_total_num = $dbh->query($sql_num)->fetchColumn();
** error_log()
   可以用它方便地记录日志。
** 中文支持
   字段中可能有中文，有两种方法可以解决中文支持问题，一种是修改数据库的配置文件，
   另一种方法是在查询时设置编码方式，建议后一种。参考文档：
   http://www.busfly.net/post/58.html

   在连接到数据库后，执行以下 sql 语句的查询:
   $sql_0 = "SET NAMES 'UTF8'";
   $sql_1 = "SET CHARACTER SET UTF8";
   $sql_2 = "SET CHARACTER_SET_RESULTS=UTF8";
   之后再进行其它操作。
* 一些函数的注意
** stream_select()
  和 Linux 下的 select() 系统调用作用一样，看 PHP 手册时看不明白，通过 man
  select 更容易理解些。
  Linux 下 select() 原型:
  int select(int nfds, 
             fd_set *readfds, 
	     fd_set *writefds, 
	     fd_set *exceptfds,
	     struct timeval *timeout);
 
  对比 PHP 下的 stream_select() 原型:
  int stream_select(array &$read, 
                    array &$write, 
		    array &$except, 
		    int $tv_sec [, int $tv_usec = 0]);

  可知，我需要通过 select() 理解 stream_select() 的作用，$read、$write、$except
  和限定时间。

  select() allow a program to monitor multiple file descriptors, waiting until
  one or more of the file descriptors become "ready" for some class of I/O
  operation (e.g., input possible). A file descriptor is considered ready if it
  is possible to perform the corresponding I/O operation (e.g., read(2)) without
  blocking.
  
  Three independent sets of file descriptors are watched. Those listed in
  /readfds/ will be watched to see if characters become available for reading
  (more precisely, to see if a read will not block; in particular, a file
  descriptor is also ready on end-of-file), those in /writefds/ will be watched
  to see if a write will not block, and those in /exceptfds/ will be watched for
  exceptions. On exit, the sets are modified in place to indicate which file
  descriptors actually changed status. Each of the three file descriptors sets
  may be specified as *NULL* if no file descriptors are to be watched for the
  corresponding class of events.

  /timeout/ is an upper bound on the amount of time elapsed before select()
  returns. If both fields of the /timeval/ structure are zero, then select()
  returns immediatly.(This is useful for polling). If /timeout/ is *NULL* (no
  timeout), select() can block indefinitely.

  On success, select() returns the number of file descriptors contained in the
  three returned descriptor sets (that is, the total number of bits that are set
  in /readfds/, /writefds/, /exceptfds/) which may be zero if the timeout
  expires before anything interesting happends. On error, -1 is returned, an
  errno is set appropriately; the sets and timeout become undefined, so do not
  rely on their contents after an error.
<<<<<<< HEAD
** sleep() 使用时注意
  若是在多进程中使用 sleep(),如想在父进程 sleep() 一段时间，而子进程正常运行，这
  样 sleep() 可能会失效，因为子进程在退出时会向父进程发出一个信号，sleep() 可能
  在父进程接受到该信号时会退出，如下:

  <?php
  error_reporting(E_ALL);

  date_default_timezone_set("Asia/Chongqing");

  $pid = pcntl_fork();
  switch ($pid) {
  case 0:
  /* in child */
  echo "in child\n";
  exit(0);
  case -1:
  die("pcntl_fork() failed\n");
  default:
  /* in parent */
  echo "in parent\n";
  sleep(10);
  echo "after 10 seconds, parent wakes.\n";
  }

  在这个程序中，父进程不会 sleep 10 秒，会直接返回。可在子进程中运行一段代码，在
  子进程中 sleep()，这样或许可以避免 sleep() 被信号中断的问题。
  若必须使父进程 sleep 一段时间，则在 Unix 或类 Unix 平台下，使用系统提供的
  sleep 命令也可以实现。修改以上代码:

  <?php
  error_reporting(E_ALL);

  date_default_timezone_set("Asia/Chongqing");

  $pid = pcntl_fork();
  switch ($pid) {
  case 0:
  /* in child */
  echo "in child\n";
  exit(0);
  case -1:
  die("pcntl_fork() failed\n");
  default:
  /* in parent */
  echo "in parent\n";
  system("sleep 10");
  echo "after 10 seconds, parent wakes.\n";
  
** exec()
   观察如下形式:

   $suffix = "-l";
   $output = array();

   exec("ls $suffix", $output);

   foreach ($output as $item) {
	echo $item . "\n";
   }

   即可以在命令中用 PHP 变量。
* 数组
** 特殊的建立数组的方法
   除了常规的建立数组的方法，也可通过如下方法建立数组:
   
   $arr = array();

   foreach (range(0, 10) as $_v) {
      $arr[] = $_v;
   }

   foreach ($arr as $_v) {
      echo $_v . "\n";
   }
** 数组赋给另一个变量
   可直接把一个数组赋值给另一个变量，类似于普通变量之间的赋值。如:

   $arr = array(1, 2, 3, 4);
   $var = $arr;    // $var 就变成了和 $arr 一样的数组
** 数组合并的两种方法的区别
   数组合并可用 array_merge() 或 "+"，但效果不同：
   
   1) $arr = array_merge($arr_0, $arr_1);
      把两个数组合并，若 $arr_1 中含有非数值索引，且 $arr_0 也有相同的非数值索引，
      则后者中的这个值会覆盖前者。对于数值索引的元素，不影响，即 $arr_0 中和
      $arr_1 中都有数值索引的元素，它们仍旧会出现在新的数组中，只是索引值不同。
   2) $arr = $arr_0 + $arr1;
      把两个数组合并，会把相同键值的元素用 $arr_0 中的替换，而不是 $arr_1 中的。
* 设置报错
  最好每次写 PHP 时，都在开头使用
  error_reporing(E_ALL);
  来打印所有可能的出错信息。
* 使用时间时要注意的
  若在程序中需要使用时间，则需要在使用之前设置下时区，在国内一般用
  date_default_timezone_set("Asia/Chongqing");

* 打印文件、函数、行号、类名等信息
  可通过变量 __FILE__、__FUNCTION__、__LINE__、__CLASS__ 来获取。
* phpize
  有时使用 phpize 时可能会出现如下的错误:

  Cannot find build files at '/usr/local/lib/php/build'. Please check your PHP
  installation.

  找下 phpize 的位置，通过绝对路径来使用 phpize.
* php-config
  我在安装 xhprof 过程中遇到过因为 php-config 不能用的问题，通过
  $ lcoate php-config
  发现有两个位置含有 php-config 命令，试了试之后发现只有一个可以正确使用，于是把
  出现问题的那个删除了。
  在有问题的情况下，make 时会提示源码错误。以后在出现这种问题时，注意下
  php-config 是否能够正确使用。

  我按照 gearman 官网上的资料安装 gearman 的 php 扩展时，提示 zend_internal 之类
  的错误，也是因为 php-config 的问题，在 configure 时通过指定良好的 php-config
  可以解决这个问题:
  $ ./configure --with-php-config=/usr/bin/php-config
* 子进程被 kill 掉时文件锁的问题
  在子进程中对一个文件加上 LOCK_EX|LOCK_NB 锁，当子进程被其它进程通过
  posix_kill() 发出 SIGKILL 或 SIGTERM 信号后，被子进程加锁的文件不会自动解锁，
  除非是子进程自己退出。
* Web API
** 获取完整的参数数据
   以
   http://localhost/api.php?url=http://api.douban.com/test.php?arg1=242&arg2=24&follow=y
   其中 http://localhost/api.php 是 API，通过 $_GET['url'] 获得不了用户传入的完
   整的 url，只能获得用户传入的 url 的部分，如本例中的
   http://api.douban.com/test.php?arg1=242 之后的就获得不了。这是因为 url 中是以
   & 作为参数的分隔符。
   解决方法是，可用 $_SERVER['QUERY_STRING'] 来获得用户传入的所有参数，然后自己
   解析字符串。
* HTML 解析相关
  可通过 DOMDocument 类来解析 HTML 文件，其中涉及到 CSS selector 或 xpath 来快速
  定位某个元素。
  >>>>>>> aebaab8201adab903c58041562553f75a1bb7b65
* break 加参数
  跳出循环时常用 break，它可加数字参数，表示跳出几层循环，不加参数时等价于
  "break 1"，即跳出最近的一层循环。
* 将函数名赋o变量
  PHP 中的这种做法类似于 C\C++ 中将函数名赋o一个变量，简单的例子如下：

  function test($i = 1)
  {
	echo "In function $i.\n";
  }

  $func = "test";
  echo $func(2);
* json 相关
  注意 json 中 key 和 value 若是字符串，必须用双引号。
  可通过如下两种方式访问解析后的 json 数据:

  $json_raw = '{"flyer":"flyer0", "flx":"flx0"}';
  $json_dec = json_decode($json_raw);

  echo "Test0:\n";
  echo $json_dec->{'flyer'} . "\n";
  echo $json_dec->{'flx'} . "\n\n";

  echo "Test1:\n";
  foreach ($json_dec as $_k => $_v) {
	echo $_k . " : " . $_v . "\n";
  }
* 保证进程唯一性
  有时需要保证在一段时间内，同一个程序只能运行一次，即不能在该程序运行期间再次运
  行该程序，解决方案是采用文件锁。
  在第一次运行程序时，建立一个文本文件，在对该文件写入数据(通常是 pid)前，要先对
  文件加上 _互斥锁_ 和 _非阻断锁_ ，若能获得锁，则可写入数据，否则表示该程序已经
  运行了。当程序结束时，会自动释放锁。
* curl
** 并行抓取及多资源命名技巧
   通过采用 curl_multi_* 系列的函数，可以实现并行抓取，这比串行抓取的效率高了很
   多。
   有个问题是对每个 curl 资源命名的问题，可通过数组来实现，即每个 curl 资源都是
   数组的一个元素，这样避免了命名的困难。如下例

   <?php
   error_reporting(E_ALL | E_STRICT);

   $urls = array("http://www.dangdang.com",
        	  "http://www.amazon.com",
		  "http://www.amazon.cn",
		  "http://www.360buy.com",
		  "http://xdlinux.info",
		  "http://weibo.com");
   $user_agent = "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.57 Safari/536.11";
   $curl_options = array(CURLOPT_HEADER         => 0,
                         CURLOPT_AUTOREFERER    => 1,
			 CURLOPT_FOLLOWLOCATION => 1,
			 CURLOPT_FAILONERROR    => 1,
			 CURLOPT_RETURNTRANSFER => 1,
			 CURLOPT_USERAGENT      => $user_agent);
   $curl_arr = array();

   $mh = curl_multi_init();
   foreach ($urls as $_k => $_url) {
	$curl_arr[$_k] = curl_init($_url);
	curl_setopt_array($curl_arr[$_k], $curl_options);
	curl_multi_add_handle($mh, $curl_arr[$_k]);
   }

   $running = NULL;
   do {
	curl_multi_exec($mh, $running);
   } while ($running > 0);

   foreach ($curl_arr as $_k => $_ch) {
	var_dump(curl_multi_getcontent($curl_arr[$_k]));
   }

   foreach ($curl_arr as $ch) {
	curl_multi_remove_handle($mh, $ch);
   }

   curl_multi_close($mh);
** curl_multi_
*** 获取值
    对于这个函数族，即使在设置 curl 参数时设置了 CURLOPT_FAILONERROR，通过
    curl_multi_getcontent() 在 curl 发生错误时不能获得任何信息，但可以通过
    curl_multi_info_read() 来获取最后一次执行时的信息。
*** 注意事项
    在同时对 100 个以上的 url 进行操作时，这个函数可能会有些问题，一般不要超过这
    个数。
    http://stackoverflow.com/questions/7776833/curl-multi-threading
    解决方法可参考:
    http://www.onlineaspect.com/2009/01/26/how-to-use-curl_multi-without-blocking/
* 作用域
** 包含另一文件时在函数中的作用域
   当在一个文件中包含另一个文件，而在本文件的函数中需要使用另一个文件中的变量，
   则需要在本文件的函数中使用 global 关键字声明。
   除了这种情况外，在本文件其他地方均可直接使用另一个文件中的变量。
* Memcached 
** 不要以顺序数字作为 key
   如下两段代码，第一段可以得到结果，第二段没有返回结果：

   片段一：
   $mc = new Memcached();
   $mc->addServer("127.0.0.1", 11211);

   $data_arr = array("key1" => "flyer",
                     "key2" => "flx",
		     "key3" => "dangdang");

   $mc->setMulti($data_arr);

   $res_arr = $mc->getMulti(array("key1", "key2", "key3"));
   var_dump($res_arr);

   片段二：
   $mc = new Memcached();
   $mc->addServer("127.0.0.1", 11211);

   $data_arr = array("1" => "flyer",
		    "2" => "flx",
		    "3" => "dangdang");

   $mc->setMulti($data_arr);

   $res_arr = $mc->getMulti(array("key1", "key2", "key3"));
   var_dump($res_arr);
