* 变量(PHP、JS)
  PHP 所有的变量都是以 '$' 号开头.
  
  JS 的变量以字母或下划线开头。
* 打印数据(PHP、JS)
  PHP 打印数据常用 echo、print 等。

  JS 打印数据常用 document.write() 等。
* 字符串连接(PHP、JS)
  PHP 用 '.' 连接字符串，可用 '+' 和 array_merge() 来合并数组。

  JS 用 '+' 连接字符串。
* 字符串和数字相加(PHP、JS)
  PHP 中，字符串和数组相加，若字符串也是数字，则作为数字做加法运算。若字符串由数
  字和非数字组成，则取首次出现非数字的位置起的前面的数字作加法运算。

  JS 中，字符串和数组相加，则都作为字符串，作字符串的连接操作。
* 逻辑判断运算符(PHP、JS)
  PHP 中可用 "&&"、"||"、"!"、"and"、"or" 作逻辑判断。

  JS 中可用 "&&"、"||"、"!" 作逻辑判断。
* ?: 运算符(PHP、JS、Python)
  PHP、JS 中都有这个三元运算符。

  Python 中没有这个三元运算符。

* 大小写敏感(PHP、JS、HTML)
  PHP 只有变量名对大小写敏感，函数名等对大小写不敏感。
  
  JS 对大小写敏感。

  HTML 对大小写不敏感。
* === 比较(PHP、JS)
  PHP 和 JS 中都有这个比较运算符，意思是同时比较 _值_ 和 _类型_ 。
  在 PHP 和 JS 中， == 只表示比较值，不比较类型。
  类似的还有 "!=="
* 语句行的结束(PHP、JS、Python、Perl)
  PHP、Perl 都是用 ";" 号表示一行语句的结束。

  Python 语句行的结束不用加任何符号来表示。

  JS 既可以用 ";" 也可以不加任何符号表示一行语句的结束。
* break 语句(PHP、JS、Python、Perl)
  在这几种语言中，break 的用法基本上都相同，只是在 PHP 中增加了一个功能，即:
  break n;
  其中，n 是数字，这条语句表示要跳出几层循环，在 PHP 中，break 不加参数时表示只
  跳出最近的一层循环。

* 数组(PHP、JS)
  PHP 中建立数组有多种方式，常见的有：
  1) $arr = array(1, 2, 3, 4);
  2) $arr = array();
     $arr[] = 1;
     $arr[] = 2;
  3) $arr = array("key1"=>1, "key2"=>2);
  4) $arr = array();
     $arr["key1"] = 1;
     $arr["key2"] = 2;

  JS 中建立数组的方式为：
  arr = new Array();
  arr[0] = 1;
  arr[1] = 2;
* 迭代遍历（PHP、JS）
  PHP 中通过 foreach() 的方式来迭代遍历数组，如
  foreach ($arr as $elem) {}

  JS 中通过 for...in... 的方式迭代遍历数组，如
  for (elem in arr) {}
